### ISSUE TITLE
hb_AdoRddExistsTable should return booelan

### ISSUE THREAD

**Issue by alencar** [AHFERREIRA/adordd#2]
As per README (#a7ef9bf21fc0d77973954d9f376846cdb7b36fa9)
...
hb_AdoRddExistsTable( oCon,cTable, cIndex,cView )
Returns .t. if exist any on the DB

But it returns numeric in Harbour  3.2.0dev (r1409231118)

╔[■]═════════════════════════════════════════════════════ Command
║> ? csql := hb_adoRddExistsTable( ,"table1")
║               1
║>

┌[■]────────────────────────────────────────────────── Monitor: Local
│0) CSQL <Local, N>:          1
└─────────────────────────────────────────────────────────────

It should return .T. or .F.

The code below In TryAdo.PRG around line 88:

IF !hb_adoRddExistsTable( ,"table1")

Will result in:
┌────────────────────────────────┐
│   Error BASE/1066  Argument error: conditional  
│  
│                       Quit  
└────────────────────────────────┘

**Comment by AHFERREIRA** [comment]
You have not a valid connection!
Nevertheless Ill correct to return .F. in this case also.
Please replace in ADOFILE

 IF !ADOCON_CHECK()
      RETURN lRet //HB_FAILURE

   ENDIF
